[package]
name = "cs-dust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.4.0"
pest_derive = "2.4.0"
pest_consume = "1.1.1"
lazy_static = "1.4.0"
walkdir = "2"
truthy = "1.1.0"
